version: '3'
services:
  web:
    #build: .
    build:
      context: .
      dockerfile: Dockerfile.dev
    
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
   
   # 2nd service to just run tests
   
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
      
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm","run","test"]
    
    
    